language: common-lisp

branches:
  only:
    - master

env:
  global:
    - PATH=~/.roswell/bin:$PATH
  matrix:
    - LISP=sbcl-bin
    - LISP=sbcl-bin/1.3.3 # CS Academy
    - LISP=sbcl-bin/1.1.15

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - git clone --depth=1 https://gitlab.common-lisp.net/asdf/asdf.git ~/lisp/asdf

script:
  - LISP_COMMAND="ros run -- --script" sh test/run-tests.sh

sudo: required
