language: common-lisp

branches:
  only:
    - master

env:
  global:
    - PATH=~/.roswell/bin:$PATH
  matrix:
    - LISP=sbcl-bin
    - LISP=sbcl-bin/1.3.3 # CS Academy
    - LISP=sbcl-bin/1.2.4 # the oldest SBCL that can be successfully installed

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh

script:
  - LISP_COMMAND="ros run -- --script" sh test/run-tests.sh

sudo: required
